/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    BiliUser: typeof import('./src/components/BiliUser.vue')['default']
    IFluentQuestion28Filled: typeof import('~icons/fluent/question28-filled')['default']
    IFluentSearch28Filled: typeof import('~icons/fluent/search28-filled')['default']
    IMaterialSymbolsChromeMinimizeRounded: typeof import('~icons/material-symbols/chrome-minimize-rounded')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    'IQuill:expand': typeof import('~icons/quill/expand')['default']
    IQuillCollapse: typeof import('~icons/quill/collapse')['default']
    IQuillExpand: typeof import('~icons/quill/expand')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceBar: typeof import('./src/components/SpaceBar.vue')['default']
  }
}
